version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android

    steps:
      - checkout

      - run:
          name: Chmod permissions for gradlew
          command: sudo chmod +x ./gradlew

      - run:
          name: Run ktlint
          command: ./gradlew ktlintCheck
      - store_artifacts:
          path: build/reports

      - run:
          name: Run Unit tests
          command: ./gradlew testDebugUnitTest
      - store_artifacts:
          path: build/reports
      - store_test_results:
          path: build/test-results